### PR TITLE
Update to reflect changes to Corda v3.0

### PR DESCRIPTION
**Pull request by bennytanr3**
Update to reflect changes to Corda v3.0

Module 1 changes: slide 4 - clean up description
Module 2 changes: slide 106 and 107 - Remove networkmap node
Module 3 changes: slide 4,5,9,11,13,15 (removed slide 16 - not using traders demo) - clean up text/URLs + replace traders demo with example
Module 5 changes: slide 26, 30 - clean up code/title
Module 9 changes: slide 4, 33 - Remove networkmap node

### CODE REVIEW

**Comment by amoothart** [comment]
Module 2 #106: What are we actually recommending customers do to facilitate the network map service in V3? Telling teams to build their own http service feels rather unnecessary and may not be well received.

Module 3 #4: Corda is not updated monthly anymore
Module 3: Honestly I've never used this module because I describe these actions verbally.

Module 5 #26: participants is a List<Party>

Overall the lack of a network map feels like a significant gap in the V3 story. Instead of simply removing the node and causing lots of questions about what to do instead let's proactively provide the network map best practice.

**Comment by ivanr3** [comment]
Shall we remove module 3 (as well as 4 and 10)?

**Comment by bennytanr3** [comment]
Module 2: Well we aren't recommending anything, just telling them what the network looks like. Its just like the doorman. In development of CorDapp its entirely optional, but probably not in the context of deployment. I would argue that our introduction training is to get acquainted with CorDapp development rather than deployment. 

Module 3 #4: Corda is not updated monthly anymore (noted
Module 3: I have used this but not module 4 (prefer to white board). Anyway removing it feels more like updating the syllabus which we are going to do later. Suggest to just stick to it until we overhaul the entire syllabus.

Module 5 #26: override val participants: List<Party> get() = listOf(lender, borrower) - only change i saw was to swap the filter back to Party from AbstractParty.

**Comment by amoothart** [comment]
@ivanr3 Let's hold off on removal for a major refactor of slides. I'd like to take a try at this in the next couple weeks.

@bennytanr3 The problem with simply removing the network map is all my latest trainings have been people focused on deployment. People have been much less interested in how to code cordapps (PoCs) and more interested in how to deploy (production).

I actually don't know what the correct network map usage in V3 is because all I have done is a local bootstrap. Ivan or Ben do you know what a V3 deployed Network Map Service looks like? I know Stefano put together a service to serve node.confs but I hope we don't have to teach that.

@bennytanr3 can you commit the couple small tweaks?

**Pull request closed without merging**
